name: cooky

networks:
  default:
    name: cooky

services:
  app:
    build:
      context: .
    image: cooky_app
    container_name: cooky_app
    environment:
      - DATABASE_URL=postgresql://${COOKY_USER:-cooky}:${COOKY_PASSWORD:-cooky}@postgres:5432/${COOKY_DATABASE:-cooky}?schema=public
      - NUXT_AUTH_JS_SECRET=${AUTH_SECRET:-cooky}
      - NUXT_PUBLIC_AUTH_JS_BASE_URL=http://localhost:8080
      - NUXT_FILE_STORAGE_PATH=/var/lib/cooky/data
      - NUXT_FILE_STORAGE_SECRET=${FILE_STORAGE_SECRET:-cooky}
    ports:
      - "8080:8080"
    volumes:
      - ./.storage:/var/lib/cooky/data
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: prisma/Dockerfile
    image: cooky_postgres
    container_name: cooky_postgres
    environment:
      - POSTGRES_USER=${ROOT_USER:-root}
      - POSTGRES_PASSWORD=${ROOT_PASSWORD:-root}
      - POSTGRES_DB=${COOKY_DATABASE:-cooky}
      - COOKY_USER=${COOKY_USER:-cooky}
      - COOKY_PASSWORD=${COOKY_PASSWORD:-cooky}
      - FILE_STORAGE_PATH=/var/lib/cooky/data
      - FILE_STORAGE_SECRET=${FILE_STORAGE_SECRET:-cooky}
    ports:
      - "5432:5432"
    volumes:
      - ./package.json:/docker-entrypoint-initdb.d/package.json
      - ./package-lock.json:/docker-entrypoint-initdb.d/package-lock.json
      - ./tsconfig.json:/docker-entrypoint-initdb.d/tsconfig.json
      - ./prisma:/docker-entrypoint-initdb.d/prisma
      - cooky_database:/var/lib/postgresql/data
      - ./server/utils:/docker-entrypoint-initdb.d/server/utils
      - ./.storage:/var/lib/cooky/data

volumes:
  cooky_database:
    name: cooky_database
