apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cooky
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/cooky-recipes/docker/cooky:latest
          name: cooky-app
          resources:
            limits:
              memory: 4G
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: database-url
            - name: NUXT_AUTH_JS_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: auth-secret
            - name: NUXT_PUBLIC_AUTH_JS_BASE_URL
              value: https://cooky.recipes
            - name: NUXT_FILE_STORAGE_PATH
              value: /var/lib/cooky/data
            - name: NUXT_FILE_STORAGE_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: file-storage-secret
          volumeMounts:
            - name: storage
              mountPath: /var/lib/cooky/data
      volumes:
        - name: storage
          csi:
            driver: gcsfuse.run.googleapis.com
            readOnly: false
            volumeAttributes:
              bucketName: cooky-recipes.appspot.com
      serviceAccountName: service-cooky@cooky-recipes.iam.gserviceaccount.com
